FROM python:3.9-slim
RUN pip install --no-cache-dir streamlit requests
WORKDIR /app
COPY . /app
EXPOSE 8501
ENV BACKEND_URL=http://localhost:5000
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
