# Namespace for Backend
apiVersion: v1
kind: Namespace
metadata:
  name: backend

---

# Namespace for Frontend
apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---

# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend  # Backend runs in this namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/hardy-tine-435523-b0/backend  # Replace with your actual image
        ports:
        - containerPort: 5000

---

# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend  # Backend service in its namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend  # Frontend runs in this namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/hardy-tine-435523-b0/frontend  # Replace with your actual image
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: "http://backend-service.backend"  # Backend service referenced with namespace

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
